# Generated by Django 2.2.5 on 2019-09-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
